routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::group(['middleware' => ['auth']], function (){
    Route::get('/home', 'HomeController@index')->name('home');
    Route::resource('/shoes', 'ShoeController', ['except' => ['show']]);
    Route::resource('/providers', 'ProviderController', ['except' => ['show']]);
    Route::resource('/cashsales', 'CashSaleController', ['except' => ['show']]);
    Route::resource('/creditsales', 'CreditSaleController', ['except' => ['show']]);
    Route::get('/shoe_report/report', 'ShoeReportController@index')->name('report');
    Route::get('/shoe_report/report/pdf', 'ShoeReportController@pdf');
    Route::get('/sale_report/report', 'SaleReportController@index')->name('sale_report');
    Route::get('/sale_report/report/pdf', 'SaleReportController@pdf');
    Route::get('/gain_report/report', 'reportgainController@index')->name('report2');
    Route::get('/shoe_report/report/pdf', 'reportgainController@pdf');
});

resources/views/home.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <h2 style="color:black;">Registros</h2>
            <br>
            <div class="form-group">

                <a class="btn btn-primary btn-lg" href="{{route('shoes.index')}}" style="width:170px;height:170px;"><img src="/iconos/iconfinder.png" style="width:120px;height:120px;"><br>
                    <label class="text-center" style="font-size:17px;">Zapatos</label></a>

                <a class="btn btn-primary btn-lg" href="{{route('providers.index')}}" style="width:170px;height:170px;"><img src="/iconos/proovedor.png" style="width:120px;height:120px;"><br>
                    <label class="text-center" style="font-size:17px;">Proovedor</label></a>

                <a class="btn btn-primary btn-lg" href="{{route('creditsales.index')}}" style="width:170px;height:170px;"><img src="/iconos/credito.png" style="width:120px;height:120px;"><br>
                    <label class="text-center" style="font-size:17px;">Crédito</label></a>

                <a class="btn btn-primary btn-lg" href="{{route('cashsales.index')}}" style="width:170px;height:170px;"><img src="/iconos/contado.png" style="width:120px;height:120px;"><br>
                    <label class="text-center" style="font-size:17px;">Contado</label></a>

            </div>
            <br>
            <h2 style="color:black;">Reportes</h2>
            <br>
            <div>
                <a href="{{route('report')}}"><button type="button" class="btn btn-primary btn-lg" style="width:170px;height:170px;"><img src="/iconos/reportezapatos.png" style="width:120px;height:120px;"><br>
                        <label class="text-center" style="font-size:17px;">Zapatos</label></button></a>

                <a href="{{route('sale_report')}}" class="btn btn-primary btn-lg" style="width:170px;height:170px;"><img src="/iconos/registroventas.png" style="width:120px;height:120px;"><br>
                    <label class="text-center" style="font-size:17px;">Ventas</label></a>


                <a href="{{route('report2')}}"><button type="button" class="btn btn-primary btn-lg" style="width:170px;height:170px;"><img src="/iconos/ganancias.png" style="width:120px;height:120px;"><br>
                        <label class="text-center" style="font-size:17px;">Ganancias</label></button></a>
            </div>
        </div>
    </div>
</div>
</div>
@endsection