routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::group(['middleware' => ['auth']], function (){
    Route::get('/home', 'HomeController@index')->name('home');
    Route::resource('/shoes', 'ShoeController', ['except' => ['show']]);
    Route::resource('/providers', 'ProviderController', ['except' => ['show']]);
    Route::resource('/cashsales', 'CashSaleController', ['except' => ['show']]);
    Route::resource('/creditsales', 'CreditSaleController', ['except' => ['show']]);
    Route::get('/shoe_report/report', 'ShoeReportController@index')->name('report');
    Route::get('/shoe_report/report/pdf', 'ShoeReportController@pdf');
    Route::get('/sale_report/report', 'SaleReportController@index')->name('sale_report');
    Route::get('/sale_report/report/pdf', 'SaleReportController@pdf');
    Route::get('/gain_report/report', 'reportgainController@index')->name('report2');
    Route::get('/shoe_report/report/pdf', 'reportgainController@pdf');
});

app/Models/CreditSale.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class CreditSale extends Model
{
    protected $fillable = ['name', 'lastname','contact', 'shoe', 'price','mont','balance', 'state'];
}

app/Http/Controllers/CreditSaleController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Models\CreditSale;
use App\Models\Shoe;
use Illuminate\Validation\Rule;
use Illuminate\Support\Facades\DB;
use App\Http\Requests\CreditSalesRequest;

class CreditSaleController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $creditsales = CreditSale::all();
        return view('creditsales.index', compact('creditsales'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $shoes = Shoe::all();
        return view('creditsales.create', compact('shoes'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $mont = $request->get('mont');
        $balance = $request->get('price') - $mont;

        $request["balance"]=$balance;
        CreditSale::create($request->all());



        return redirect('/creditsales');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $creditsales = CreditSale::find($id);
        $shoes = Shoe::all();
        return view('creditsales.edit', compact('creditsales','shoes'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $creditsales = CreditSale::find($id);
        $mont = $request->get('mont');
        $balance = $creditsales->balance - $mont;
        $mont += $creditsales->mont;
        $request["mont"]=$mont;

        $request["balance"]=$balance;

        if($balance == 0){
            $request["state"] = true;
        }

        $creditsales->update($request->all());
        return redirect('/creditsales');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        CreditSale::destroy($id);
        return redirect('/creditsales');
    }
}

resources/views/creditsales/create.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <form method="POST" action="{{ route('creditsales.store') }}">
        @csrf
        <h1 class="text-center">Añadir venta</h1>

        <div class="form-group row">
            <label for="name" class="col-md-4 col-form-label text-md-right">{{ __('Nombre') }}</label>

            <div class="col-md-6">
                <input type="text" class="form-control{{ $errors->has('name') ? ' is-invalid' : '' }}" id="name"
                    placeholder="Nombre Aquí" required name="name" value="{{ old('name') }}">
                @if ($errors->has('name'))
                <span class="invalid-feedback" role="alert">
                    <strong>{{ $errors->first('name') }}</strong>
                </span>
                @endif
            </div>
        </div>

        <div class="form-group row">
            <label for="lastname" class="col-md-4 col-form-label text-md-right">{{ __('Apellidos') }}</label>

            <div class="col-md-6">
                <input type="text" class="form-control{{ $errors->has('lastname') ? ' is-invalid' : '' }}" id="lastname"
                    placeholder="Apellidos Aquí" required name="lastname" value="{{ old('lastname') }}">
                @if ($errors->has('lastname'))
                <span class="invalid-feedback" role="alert">
                    <strong>{{ $errors->first('lastname') }}</strong>
                </span>
                @endif
            </div>
        </div>

        <div class="form-group row">
            <label for="contact" class="col-md-4 col-form-label text-md-right">{{ __('Teléfono') }}</label>

            <div class="col-md-6">
                <input type="number" class="form-control{{ $errors->has('contact') ? ' is-invalid' : '' }}" id="contact"
                    placeholder="Teléfono Aquí" required name="contact" value="{{ old('contact') }}">
                @if ($errors->has('contact'))
                <span class="invalid-feedback" role="alert">
                    <strong>{{ $errors->first('contact') }}</strong>
                </span>
                @endif
            </div>
        </div>

        <div class="form-group row">
            <label for="shoe" class="col-md-4 col-form-label text-md-right">{{ __('Zapato:') }}</label>
            <div class="col-md-6">
            <select id="shoe" name="shoe" class="form-control">
                    @if (count($shoes)>0)
                        @foreach ($shoes as $shoe)
                        <option value="{{ $shoe->name }}">{{ $shoe->name}} : {{$shoe->price}}</option>
                        @endforeach
                    @endif
            </select>
            </div>
        </div>

        <div class="form-group row">
            <label for="price" class="col-md-4 col-form-label text-md-right">{{ __('Precio') }}</label>

            <div class="col-md-6">
                <input type="text" class="form-control{{ $errors->has('price') ? ' is-invalid' : '' }}" id="price"
                    placeholder="Cantidad" required name="price" value="{{ old('price') }}">
                @if ($errors->has('price'))
                <span class="invalid-feedback" role="alert">
                    <strong>{{ $errors->first('price') }}</strong>
                </span>
                @endif
            </div>
        </div>

        <div class="form-group row">
                <label for="mont" class="col-md-4 col-form-label text-md-right">{{ __('Abono') }}</label>

                <div class="col-md-6">
                    <input type="text" class="form-control{{ $errors->has('mont') ? ' is-invalid' : '' }}" id="mont"
                        placeholder="Cantidad a abonar" required name="mont">
                    @if ($errors->has('mont'))
                    <span class="invalid-feedback" role="alert">
                        <strong>{{ $errors->first('mont') }}</strong>
                    </span>
                    @endif
                </div>
            </div>


        <div class="form-group row mb-0">
            <div class="col-md-6 offset-md-4">
                <button type="submit" class="btn btn-primary">
                    {{ __('Guardar') }}
                </button>
            </div>
        </div>
    </form>
</div>
@endsection

resources/views/creditsales/edit.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <form method="POST" action="{{ route('creditsales.update', $creditsales) }}">
        @csrf
        @method('PUT')
        <h1 class="text-center">Editar venta</h1>

        <div class="form-group row">
            <label for="name" class="col-md-4 col-form-label text-md-right">{{ __('Nombre') }}</label>

            <div class="col-md-6">
                <input type="text" class="form-control{{ $errors->has('name') ? ' is-invalid' : '' }}" id="name"
                    placeholder="Nombre Aquí" required name="name" value="{{ $creditsales->name }}">
                @if ($errors->has('name'))
                <span class="invalid-feedback" role="alert">
                    <strong>{{ $errors->first('name') }}</strong>
                </span>
                @endif
            </div>
        </div>

        <div class="form-group row">
            <label for="lastname" class="col-md-4 col-form-label text-md-right">{{ __('Apellidos') }}</label>

            <div class="col-md-6">
                <input type="text" class="form-control{{ $errors->has('lastname') ? ' is-invalid' : '' }}" id="lastname"
                    placeholder="Apellidos Aquí" required name="lastname" value="{{ $creditsales->lastname }}">
                @if ($errors->has('lastname'))
                <span class="invalid-feedback" role="alert">
                    <strong>{{ $errors->first('lastname') }}</strong>
                </span>
                @endif
            </div>
        </div>

        <div class="form-group row">
                <label for="contact" class="col-md-4 col-form-label text-md-right">{{ __('Teléfono') }}</label>

                <div class="col-md-6">
                    <input type="text" class="form-control{{ $errors->has('contact') ? ' is-invalid' : '' }}" id="contact"
                        placeholder="Cantidad" required name="contact" value="{{ $creditsales->contact }}">
                    @if ($errors->has('contact'))
                    <span class="invalid-feedback" role="alert">
                        <strong>{{ $errors->first('contact') }}</strong>
                    </span>
                    @endif
                </div>
            </div>

        <div class="form-group row">
                <label for="shoe" class="col-md-4 col-form-label text-md-right">{{ __('Zapato') }}</label>

                <div class="col-md-6">
                    <input type="text" class="form-control{{ $errors->has('shoe') ? ' is-invalid' : '' }}" id="shoe"
                          required name="shoe" value="{{ $creditsales->shoe }}" readonly>
                    @if ($errors->has('shoe'))
                    <span class="invalid-feedback" role="alert">
                        <strong>{{ $errors->first('shoe') }}</strong>
                    </span>
                    @endif
                </div>
            </div>

        <div class="form-group row">
            <label for="price" class="col-md-4 col-form-label text-md-right">{{ __('Precio') }}</label>

            <div class="col-md-6">
                <input type="text" class="form-control{{ $errors->has('price') ? ' is-invalid' : '' }}" id="price"
                    placeholder="Cantidad" required name="price" value="{{ $creditsales->price }}" readonly>
                @if ($errors->has('price'))
                <span class="invalid-feedback" role="alert">
                    <strong>{{ $errors->first('price') }}</strong>
                </span>
                @endif
            </div>
        </div>

        <div class="form-group row">
                <label for="mont" class="col-md-4 col-form-label text-md-right">{{ __('Abonar') }}</label>

                <div class="col-md-6">
                    <input type="text" class="form-control{{ $errors->has('mont') ? ' is-invalid' : '' }}" id="mont"
                         required name="mont">
                    @if ($errors->has('mont'))
                    <span class="invalid-feedback" role="alert">
                        <strong>{{ $errors->first('mont') }}</strong>
                    </span>
                    @endif
                </div>
            </div>

        <div class="form-group row mb-0">
            <div class="col-md-6 offset-md-4">
                <button type="submit" class="btn btn-primary">
                    {{ __('Guardar') }}
                </button>
            </div>
        </div>
    </form>
</div>
@endsection

resources/views/creditsales/index.blade.php
@extends('layouts.app')
@section('content')
<div class="container">
    <h1>Venta a credito</h1>
    <a class="btn btn-success mb-2" href="{{ route('creditsales.create') }}">Nueva venta</a>
    @if (count($creditsales)>0)
    <table class="table table-striped table-bordered">
        <tr>
            <th>Nombre</th>
            <th>Apellido</th>
            <th>Teléfono</th>
            <th>Zapato</th>
            <th>Precio Zapato</th>
            <th>Abonado</th>
            <th>Saldo actual</th>
            <th>Acciones</th>
        </tr>
        @foreach ($creditsales as $item)
        @if($item->state==false)
        <tr>
            <td>{{ $item->name }}</td>
            <td>{{ $item->lastname }}</td>
            <td>{{ $item->contact }}</td>
            <td>{{ $item->shoe }}</td>
            <td>{{ $item->price }}</td>
            <td>{{ $item->mont }}</td>
            <td>{{ $item->balance }}</td>

            <td>
                <div class="form-row">
                    <div class="col-auto">
                        <a href="/creditsales/{{$item->id}}/edit " class="btn btn-primary">Editar</a>
                    </div>
                </div>
            </td>
        </tr>
        @endif
        @endforeach
    </table>
    @else
    <li>Datos no disponibles</li>
    @endif
</div>
@endsection