routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::group(['middleware' => ['auth']], function (){
    Route::get('/home', 'HomeController@index')->name('home');
    Route::resource('/shoes', 'ShoeController', ['except' => ['show']]);
    Route::resource('/providers', 'ProviderController', ['except' => ['show']]);
    Route::resource('/cashsales', 'CashSaleController', ['except' => ['show']]);
    Route::resource('/creditsales', 'CreditSaleController', ['except' => ['show']]);
    Route::get('/shoe_report/report', 'ShoeReportController@index')->name('report');
    Route::get('/shoe_report/report/pdf', 'ShoeReportController@pdf');
    Route::get('/sale_report/report', 'SaleReportController@index')->name('sale_report');
    Route::get('/sale_report/report/pdf', 'SaleReportController@pdf');
    Route::get('/gain_report/report', 'reportgainController@index')->name('report2');
    Route::get('/shoe_report/report/pdf', 'reportgainController@pdf');
});

app/Models/Shoe.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Shoe extends Model
{
    protected $fillable = ['code', 'name', 'price'];
}

app/Http/Controllers/ShoeController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Models\Shoe;
use Illuminate\Validation\Rule;
use Illuminate\Support\Facades\DB;
use App\Http\Requests\ShoesRequest;

class ShoeController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $shoes = Shoe::all();
        return view('shoes.index', compact('shoes'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('shoes.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        Shoe::create($request->all());
        return redirect('/shoes');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $shoe = Shoe::find($id);
        return view('shoes.edit', compact('shoe'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $shoe = Shoe::find($id);
        $request->validate([
            'code' => ['required', 'numeric', Rule::unique('shoes')->ignore($shoe->id)],
            'name' => ['required', 'string', 'max:255'],
            'price' => ['required', 'numeric'],
        ]);

        $shoe->update($request->all());
        return redirect('/shoes');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        Shoe::destroy($id);
        return redirect('/shoes');
    }
}

resources/views/shoes/create.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <form method="POST" action="{{ route('shoes.store') }}">
        @csrf
        <h1 class="text-center">Añadir Zapato</h1>

        <div class="form-group row mt-5">
            <label for="code" class="col-md-4 col-form-label text-md-right">{{ __('Código') }}</label>

            <div class="col-md-6">
                <input type="number" required class="form-control{{ $errors->has('code') ? ' is-invalid' : '' }}"
                    id="code" placeholder="Código Aquí" name="code" value="{{ old('code') }}">
                @if ($errors->has('code'))
                <span class="invalid-feedback" role="alert">
                    <strong>{{ $errors->first('code') }}</strong>
                </span>
                @endif
            </div>
        </div>
        <div class="form-group row">
            <label for="name" class="col-md-4 col-form-label text-md-right">{{ __('Nombre') }}</label>

            <div class="col-md-6">
                <input type="text" class="form-control{{ $errors->has('name') ? ' is-invalid' : '' }}" id="name"
                    placeholder="Nombre Aquí" required name="name" value="{{ old('name') }}">
                @if ($errors->has('name'))
                <span class="invalid-feedback" role="alert">
                    <strong>{{ $errors->first('name') }}</strong>
                </span>
                @endif
            </div>
        </div>

        <div class="form-group row">
            <label for="price" class="col-md-4 col-form-label text-md-right">{{ __('Precio') }}</label>

            <div class="col-md-6">
                <input type="text" class="form-control{{ $errors->has('author') ? ' is-invalid' : '' }}" id="price"
                    placeholder="Precio Aquí" required name="price" value="{{ old('price') }}">
                @if ($errors->has('name'))
                <span class="invalid-feedback" role="alert">
                    <strong>{{ $errors->first('price') }}</strong>
                </span>
                @endif
            </div>
        </div>

        <div class="form-group row mb-0">
            <div class="col-md-6 offset-md-4">
                <button type="submit" class="btn btn-primary">
                    {{ __('Guardar') }}
                </button>
            </div>
        </div>
    </form>
</div>
@endsection

resources/views/shoes/edit.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <form method="POST" action="{{ route('shoes.update', $shoe) }}">
        @csrf
        @method('PUT')
        <h1 class="text-center">Editar Zapato</h1>

        <div class="form-group row mt-5">
            <label for="code" class="col-md-4 col-form-label text-md-right">{{ __('Código') }}</label>

            <div class="col-md-6">
                <input type="number" required class="form-control{{ $errors->has('code') ? ' is-invalid' : '' }}"
                    id="code" placeholder="Código Aquí" name="code" value="{{ $shoe->code }}">
                @if ($errors->has('code'))
                <span class="invalid-feedback" role="alert">
                    <strong>{{ $errors->first('code') }}</strong>
                </span>
                @endif
            </div>
        </div>
        <div class="form-group row">
            <label for="name" class="col-md-4 col-form-label text-md-right">{{ __('Nombre') }}</label>

            <div class="col-md-6">
                <input type="text" class="form-control{{ $errors->has('name') ? ' is-invalid' : '' }}" id="name"
                    placeholder="Nombre Aquí" required name="name" value="{{ $shoe->name }}">
                @if ($errors->has('name'))
                <span class="invalid-feedback" role="alert">
                    <strong>{{ $errors->first('name') }}</strong>
                </span>
                @endif
            </div>
        </div>

        <div class="form-group row">
            <label for="price" class="col-md-4 col-form-label text-md-right">{{ __('Precio') }}</label>

            <div class="col-md-6">
                <input type="text" class="form-control{{ $errors->has('price') ? ' is-invalid' : '' }}" id="price"
                    placeholder="Precio Aquí" required name="price" value="{{ $shoe->price }}">
                @if ($errors->has('name'))
                <span class="invalid-feedback" role="alert">
                    <strong>{{ $errors->first('price') }}</strong>
                </span>
                @endif
            </div>
        </div>

        <div class="form-group row mb-0">
            <div class="col-md-6 offset-md-4">
                <button type="submit" class="btn btn-primary">
                    {{ __('Guardar') }}
                </button>
            </div>
        </div>
    </form>
</div>
@endsection

resources/views/shoes/index.blade.php
@extends('layouts.app')
@section('content')
<div class="container">
    <h1>Zapatos</h1>
    <a class="btn btn-success mb-2" href="{{ route('shoes.create') }}">Nuevo Zapato</a>
    @if (count($shoes)>0)
    <table class="table table-striped table-bordered">
        <tr>
            <th>Codigo</th>
            <th>Nombre</th>
            <th>Precio</th>
            <th>Acciones</th>
        </tr>
        @foreach ($shoes as $shoe)
        <tr>
            <td>{{ $shoe->code }}</td>
            <td>{{ $shoe->name }}</td>
            <td>{{ $shoe->price }}</td>
            <td>
                <div class="form-row">
                    <div class="col-auto">
                        <a href="/shoes/{{$shoe->id}}/edit " class="btn btn-primary">Editar</a>
                    </div>
                    <div class="col-auto">
                        <form method="POST" action="{{ route('shoes.destroy', $shoe) }}">
                            @csrf
                            @method('DELETE')
                            <button class="btn btn-danger">Eliminar</button>
                        </form>
                    </div>
                </div>
            </td>
        </tr>
        @endforeach
    </table>
    @else
    <li>Datos no disponibles</li>
    @endif
</div>
@endsection