routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::group(['middleware' => ['auth']], function (){
    Route::get('/home', 'HomeController@index')->name('home');
    Route::resource('/shoes', 'ShoeController', ['except' => ['show']]);
    Route::resource('/providers', 'ProviderController', ['except' => ['show']]);
    Route::resource('/cashsales', 'CashSaleController', ['except' => ['show']]);
    Route::resource('/creditsales', 'CreditSaleController', ['except' => ['show']]);
    Route::get('/shoe_report/report', 'ShoeReportController@index')->name('report');
    Route::get('/shoe_report/report/pdf', 'ShoeReportController@pdf');
    Route::get('/sale_report/report', 'SaleReportController@index')->name('sale_report');
    Route::get('/sale_report/report/pdf', 'SaleReportController@pdf');
    Route::get('/gain_report/report', 'reportgainController@index')->name('report2');
    Route::get('/shoe_report/report/pdf', 'reportgainController@pdf');
});

app/Models/provider.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class provider extends Model
{
    protected $fillable = ['name', 'lastname', 'phone'];
}

app/Http/Controllers/ProviderController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Models\Provider;
use Illuminate\Validation\Rule;
use Illuminate\Support\Facades\DB;
use App\Http\Requests\ProvidersRequest;


class ProviderController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $providers = Provider::all();
        return view('providers.index', compact('providers'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('providers.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        Provider::create($request->all());
        return redirect('/providers');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $providers = Provider::find($id);
        return view('providers.edit', compact('providers'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $provider = Provider::find($id);
        $request->validate([
            'name' => ['required', 'string', 'max:255'],
            'lastname' => ['required', 'string', 'max:255'],
            'phone' => ['required', 'numeric','max:10'],
        ]);

        $provider->update($request->all());
        return redirect('/providers');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        Provider::destroy($id);
        return redirect('/providers');
    }
}

resources/views/providers/create.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <form method="POST" action="{{ route('providers.store') }}">
        @csrf
        <h1 class="text-center">Añadir Proveedor</h1>

        <div class="form-group row">
            <label for="name" class="col-md-4 col-form-label text-md-right">{{ __('Nombre') }}</label>

            <div class="col-md-6">
                <input type="text" class="form-control{{ $errors->has('name') ? ' is-invalid' : '' }}" id="name"
                    placeholder="Nombre Aquí" required name="name" value="{{ old('name') }}">
                @if ($errors->has('name'))
                <span class="invalid-feedback" role="alert">
                    <strong>{{ $errors->first('name') }}</strong>
                </span>
                @endif
            </div>
        </div>
        
        <div class="form-group row">
            <label for="lastname" class="col-md-4 col-form-label text-md-right">{{ __('Apellidos') }}</label>

            <div class="col-md-6">
                <input type="text" class="form-control{{ $errors->has('lastname') ? ' is-invalid' : '' }}" id="lastname"
                    placeholder="Apellidos Aquí" required name="lastname" value="{{ old('lastname') }}">
                @if ($errors->has('lastname'))
                <span class="invalid-feedback" role="alert">
                    <strong>{{ $errors->first('lastname') }}</strong>
                </span>
                @endif
            </div>
        </div>

        <div class="form-group row">
            <label for="phone" class="col-md-4 col-form-label text-md-right">{{ __('Teléfono') }}</label>

            <div class="col-md-6">
                <input type="text" class="form-control{{ $errors->has('phone') ? ' is-invalid' : '' }}" id="phone"
                    placeholder="Teléfono Aquí" required name="phone" value="{{ old('phone') }}">
                @if ($errors->has('phone'))
                <span class="invalid-feedback" role="alert">
                    <strong>{{ $errors->first('phone') }}</strong>
                </span>
                @endif
            </div>
        </div>

        <div class="form-group row mb-0">
            <div class="col-md-6 offset-md-4">
                <button type="submit" class="btn btn-primary">
                    {{ __('Guardar') }}
                </button>
            </div>
        </div>
    </form>
</div>
@endsection

resources/views/providers/edit.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <form method="POST" action="{{ route('providers.update', $providers) }}">
        @csrf
        @method('PUT')
        <h1 class="text-center">Editar proveedor</h1>

        <div class="form-group row mt-5">
            <label for="name" class="col-md-4 col-form-label text-md-right">{{ __('Nombre') }}</label>

            <div class="col-md-6">
                <input type="text" required class="form-control{{ $errors->has('name') ? ' is-invalid' : '' }}"
                    id="name" placeholder="Nombre Aquí" name="name" value="{{ $providers->name }}">
                @if ($errors->has('name'))
                <span class="invalid-feedback" role="alert">
                    <strong>{{ $errors->first('name') }}</strong>
                </span>
                @endif
            </div>
        </div>

        <div class="form-group row">
            <label for="lastname" class="col-md-4 col-form-label text-md-right">{{ __('Apellidos') }}</label>

            <div class="col-md-6">
                <input type="text" class="form-control{{ $errors->has('lastname') ? ' is-invalid' : '' }}" id="lastname"
                    placeholder="Apellidos Aquí" required name="lastname" value="{{ $providers->lastname }}">
                @if ($errors->has('lastname'))
                <span class="invalid-feedback" role="alert">
                    <strong>{{ $errors->first('lastname') }}</strong>
                </span>
                @endif
            </div>
        </div>

        <div class="form-group row">
            <label for="phone" class="col-md-4 col-form-label text-md-right">{{ __('Teléfono') }}</label>

            <div class="col-md-6">
                <input type="text" class="form-control{{ $errors->has('phone') ? ' is-invalid' : '' }}" id="phone"
                    placeholder="Teléfono Aquí" required name="phone" value="{{ $providers->phone }}">
                @if ($errors->has('phone'))
                <span class="invalid-feedback" role="alert">
                    <strong>{{ $errors->first('phone') }}</strong>
                </span>
                @endif
            </div>
        </div>

        <div class="form-group row mb-0">
            <div class="col-md-6 offset-md-4">
                <button type="submit" class="btn btn-primary">
                    {{ __('Guardar') }}
                </button>
            </div>
        </div>
    </form>
</div>
@endsection

resources/views/providers/index.blade.php
@extends('layouts.app')
@section('content')
<div class="container">
    <h1>Proveedores</h1>
    <a class="btn btn-success mb-2" href="{{ route('providers.create') }}">Nuevo Proveedor</a>
    @if (count($providers)>0)
    <table class="table table-striped table-bordered">
        <tr>
            <th>Nombre</th>
            <th>Apellido</th>
            <th>Telefono</th>
            <th>Acciones</th>
        </tr>
        @foreach ($providers as $provider)
        <tr>
            <td>{{ $provider->name }}</td>
            <td>{{ $provider->lastname }}</td>
            <td>{{ $provider->phone }}</td>
            <td>
                <div class="form-row">
                    <div class="col-auto">
                        <a href="/providers/{{$provider->id}}/edit " class="btn btn-primary">Editar</a>
                    </div>
                    <div class="col-auto">
                        <form method="POST" action="{{ route('providers.destroy', $provider) }}">
                            @csrf
                            @method('DELETE')
                            <button class="btn btn-danger">Eliminar</button>
                        </form>
                    </div>
                </div>
            </td>
        </tr>
        @endforeach
    </table>
    @else
    <li>Datos no disponibles</li>
    @endif
</div>
@endsection